name: inngage_plugin_example
description: Demonstrates how to use the inngage_plugin plugin.
version: 1.0.0

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.18.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    #Firebase
 #Firebase
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  firebase_messaging: ^16.0.4

  logger: ^2.3.0
  flutter_secure_storage: ^9.2.2
  upgrader: ^11.3.1

  #AppsFlyer
  appsflyer_sdk: ^6.15.0

  #.env
  flutter_dotenv: ^6.0.0

  #localNotificaiton
  flutter_local_notifications: ^18.0.1
  #inngage_plugin: ^3.7.0
  inngage_plugin:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - .env
