name: inngage_plugin
description: Inngage Plugin for Flutter applications for marketing campaign optimization using Push Notification and In App Messages channels.
version: 4.0.0
homepage: https://inngage.com.br

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  # android and iOS getters to get platform-specific device information
  device_info_plus: ">=10.1.2 <=13.1.0"

  # firebase
  firebase_core: ">=4.2.1 <=4.10.0"
  firebase_analytics: ">=12.0.4 <=12.4.2"
  firebase_messaging: ">=16.0.4 <=16.3.0"

  # localNotificaiton
  flutter_local_notifications: ">=18.0.1 <=21.0.0"

  # launch external URLs
  url_launcher: ">=6.3.1 <=6.3.2"

  # webview
  webview_flutter: ">=4.8.0 <=4.13.1"

  # locale
  devicelocale: ">=0.8.0 <=0.9.0"

  # geolocation
  geolocator: ">=12.0.0 <=14.0.2"

  # version
  uuid: ">=4.4.1 <=4.5.3"
  shared_preferences: ">=2.3.2 <=2.5.5"
  package_info_plus: ">=8.0.2 <=10.1.0"
  advertising_id: ">=2.6.0 <=2.7.1"
  meta: ">=1.15.0 <=1.18.2"
  http: ">=1.2.1 <=1.6.0"
  logger: ">=2.3.0 <=2.7.0"
  flutter_secure_storage: ">=9.2.2 <=10.3.1"
  flutter_fortune_wheel: ">=1.3.0 <=1.3.2"
  scratcher: ">=2.5.0 <3.0.0"

dev_dependencies:
  mockito: ^5.4.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.inngage_plugin
        pluginClass: InngagePlugin
      ios:
        pluginClass: InngagePlugin

false_secrets:
  - example/ios/Runner/GoogleService-Info.plist
  - example/android/app/google-services.json
  - example/lib/firebase_options.dart
